name       : ufw
version    : 0.3.4
release    : 2
source     :
    - https://launchpad.net/ufw/0.34/0.34/+download/ufw-0.34.tar.gz : 49b512ec49e39f6d17ea679a052c54aebbe6f0640ef476577f07bb5a14cfb908
license    : GPL-3.0
summary    : Uncomplicated Firewall
description: |
    Uncomplicated Firewall, and is program for managing a netfilter firewall. It provides a command line interface and aims to be uncomplicated and easy to use.
builddeps  :
    - pkgconfig(xtables)
setup      : |
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot%
