name       : ufw
version    : 0.3.4
release    : 4
source     :
    - https://launchpad.net/ufw/0.34/0.34/+download/ufw-0.34.tar.gz : 49b512ec49e39f6d17ea679a052c54aebbe6f0640ef476577f07bb5a14cfb908
license    : GPL-3.0
component  : network.utils
summary    : Uncomplicated Firewall
description: |
    Uncomplicated Firewall, and is program for managing a netfilter firewall. It provides a command line interface and aims to be uncomplicated and easy to use.
builddeps  :
    - pkgconfig(xtables)
build      : |
    python setup.py build
install    : |
    sed -i -e 's|/lib|%libdir%|' setup.py
    python setup.py install --root=%installroot%
    chmod -R 00644 $installdir/etc/ufw/* \
                   $installdir/etc/default/ufw \
                   $installdir/%libdir%/ufw/*
    chmod 00744 $installdir/usr/sbin/ufw
    install -D -m 00644 $pkgfiles/ufw.service $installdir/%libdir%/systemd/system/ufw.service

    # enable by default, user just needs to "sudo ufw enable"
    install -d -m 00755 -D $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv %libdir%/systemd/system/ufw.service $installdir/%libdir%/systemd/system/multi-user.target.wants/ufw.service
