name       : ufw
version    : 0.36
release    : 10
source     :
    - https://launchpad.net/ufw/0.36/0.36/+download/ufw-0.36.tar.gz : 754b22ae5edff0273460ac9f57509c3938187e0cf4fb9692c6a02833fff33cfc
license    :
    - GPL-2.0-or-later
    - GPL-3.0-only
component  : network.utils
summary    : Uncomplicated Firewall
description: |
    Uncomplicated Firewall, and is program for managing a netfilter firewall. It provides a command line interface and aims to be uncomplicated and easy to use.
builddeps  :
    - pkgconfig(xtables)
build      : |
    %patch -p1 < $pkgfiles/ufw-0.35-python36.patch
    sed -i -e 's|/lib|%libdir%|' setup.py

    %python3_setup
install    : |
    %python3_install
    chmod -R 00644 $installdir/etc/ufw/* \
                   $installdir/etc/default/ufw \
                   $installdir/%libdir%/ufw/*
    chmod 00744 $installdir/usr/sbin/ufw $installdir/%libdir%/ufw/ufw-init

    install -D -m00644 shell-completion/bash $installdir/usr/share/bash-completion/completions/ufw
    install -D -m00644 $pkgfiles/ufw.service $installdir/%libdir%/systemd/system/ufw.service

    # enable by default, user just needs to "sudo ufw enable"
    install -d -m00755 -D $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv %libdir%/systemd/system/ufw.service $installdir/%libdir%/systemd/system/multi-user.target.wants/ufw.service
